apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: backend
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - envFrom:
            - configMapRef:
                name: backend-configmap
            - secretRef:
                name: backend-env-secret 
          image: ghcr.io/vijai-veerapandian/myweather-backend:1.0
          name: myweather-backend
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
