apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myweather-app
resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
