apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-audiobookshelf
spec:
  selector:
    matchLabels:
      app: cloudflared-audiobookshelf
  replicas: 2 # You could also consider elastic scaling for this deployment
  template:
    metadata:
      labels:
        app: cloudflared-audiobookshelf
    spec:
      containers:
      - name: cloudflared-audiobookshelf
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: creds
          mountPath: /etc/cloudflared/creds
          readOnly: true
      volumes:
      - name: creds
        secret:
          secretName: tunnel-credentials

      # Create a config.yaml file from the ConfigMap below.
      - name: config
        configMap:
          name: cloudflared-audiobookshelf
          items:
          - key: config.yaml
            path: config.yaml
---
# This ConfigMap is just a way to define the cloudflared config.yaml file in k8s.
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-audiobookshelf
data:
  config.yaml: |
    tunnel: audiobookshelf
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true

    ingress:
    - hostname: audiobookshelf.vijaiveerapandian.com
      service: http://audiobookshelf:3005

    - hostname: hello.example.com
      service: hello_world
    - service: http_status:404
