apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: audiobookshelf
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33

      containers:
      - image: ghcr.io/advplyr/audiobookshelf:2.17.2
        name: audiobookshelf
        ports:
          - containerPort: 3005
            protocol: TCP

        securityContext:
          allowPrivilegeEscalation: false

        envFrom:
          - configMapRef:
              name: audiobookshelf-configmap

        volumeMounts:
          - name: audiobookshelf-audiobooks
            mountPath: /audiobooks
          - name: audiobookshelf-podcasts
            mountPath: /podcasts
          - name: audiobookshelf-config
            mountPath: /config
          - name: audiobookshelf-metadata
            mountPath: /metadata
      
      restartPolicy: Always
      volumes:
        - name: audiobookshelf-audiobooks
          persistentVolumeClaim:
            claimName: audiobookshelf-audiobooks
        - name: audiobookshelf-podcasts
          persistentVolumeClaim:
            claimName: audiobookshelf-podcasts
        - name: audiobookshelf-config
          persistentVolumeClaim:
            claimName: audiobookshelf-config
        - name: audiobookshelf-metadata
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata