apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:WduEwtyEthzhitu/nGSRjEO3qonL78/TG42HjUm58HV9/IFjWCd2wydiwn8eVdwLULy4Z8qSfzVh9/+OI4TgPnTteXtDnHDRMVlIiCyaPAvQAhBnVoqSVA+Ue3dCiMyerzMmWsCFiaGpYKN8HkvKfrSNZpRVwgeNh0BCG6tb3W+mxhJ52dN3GIBqp4L3ONdOMG3m3/oiMxKHU1X1nAdj/TSTMecVLimeHDDynsEBd54SOi0Kv2HqTG/nbsUomnpOUhMWuDqEyLiYWwWg1cxgxaWVNhZ+HPbMgKnu2A8d9IVX2FVBCQ9A+VPpAFY=,iv:iNQcd73wPFJOTq7MHrlSsi5H1SWM5dc1Pk/YWzFPz8M=,tag:a26HQ+G/i1oAofTGmA9lZw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1mdd3zj2gmm4sw6h3l62dv00dp4y8uu628n6fxfax2ftmwqrdtcjq4pmwcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WUNCakp2WTVrYUpvSFlB
            Z1V2WC9Dc1FqQnBuY1krSEZKcEtoZ0IrSEJrCjJJRE5JUXExYXVIblhXK1FkVUti
            V3B3Sm1xVnFaVTJLYS9DWDk0TlVDbXMKLS0tIGNGMjdSa3FYb1kxVDEwRmIzTVhX
            ZE5MUWRaZ3dWTzlSMk9GdldETmxWM1EKopuppJUTWQzEJJD3ZutteAs4Oon1PQNw
            tDqH2UHkT3atd7h9AkEURSsbic+u2tErUymVbal5XpY2A1RJAFKBNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-23T10:17:34Z"
    mac: ENC[AES256_GCM,data:gWaBfcZFJMrG0Q8dDJPZ/r9dX+cH949WJnRUKwpKhjeOEygM0bph/ja5fdUxrKGsVT3tkVasOJiJjORL/CKXKH1FrK3ixjrIm0qsinBPYZ2dUJaEALvE+/TjLJOI8CRaIbRDmml9O+8IvebBAaea9ohXW9D3zE+suvjZxzTMrpM=,iv:bJa/RjaoyeR6DC65pN1+JkUmXVGiaul3XaYQ9vMx6j0=,tag:MGqlVjXHsFdrn8+4a4tTqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
