apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myweather
resources:
  - namespace.yaml
  - ../../base/myweather-app
  - cloudflare.yaml
  - cloudflare-secret.yaml
  - ingress.yaml
  - backend-secret.yaml
