apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app1
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 1m
  timeout: 5m

  path: ./apps/staging/audiobookshelf
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
